In [19]:
import pandas as pd
test=pd.read_csv('data/DB_final.csv')

In [20]:
test.describe()

,is_AI,gain,beauty,government,urban,art,help,optimism,strength,love,traveling,burstiness,ppl,syntax_depth,ttr,semantic_mean,semantic_std
count,51181.000000,51181.000000,51181.000000,51181.000000,51181.000000,51181.000000,51181.000000,51181.000000,51181.000000,51181.000000,51181.000000,51181.000000,51181.000000,51181.000000,51181.000000,51181.000000,51181.000000
mean,0.857467,0.004106,0.003298,0.005431,0.003864,0.004414,0.003947,0.003542,0.003918,0.002974,0.003914,10.774679,16.492210,7.360419,0.501213,0.381970,0.139455
std,0.349600,0.004986,0.006206,0.007395,0.005497,0.007873,0.005128,0.004069,0.005067,0.004268,0.004608,12.036172,27.010671,1.373940,0.080336,0.099977,0.047309
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.308495,2.000000,0.049085,-0.094639,0.000000
25%,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.959879,9.405258,6.606061,0.457483,0.338175,0.117150
50%,1.000000,0.002663,0.000000,0.002632,0.002114,0.000933,0.002571,0.002532,0.002564,0.001792,0.002740,8.586165,12.263827,7.315789,0.497175,0.391354,0.138817
75%,1.000000,0.006135,0.003597,0.008152,0.005587,0.005089,0.005736,0.005398,0.005650,0.004484,0.005731,10.737315,16.757509,8.000000,0.537975,0.439736,0.162511
max,1.000000,0.053211,0.067194,0.076923,0.065217,0.095238,0.111111,0.053619,0.050265,0.076923,0.100000,504.745570,2080.797852,56.545455,1.000000,0.889261,0.546815

In [22]:
test.columns.to_list()

['Text',
 'model_builder',
 'is_AI',
 'gain',
 'beauty',
 'government',
 'urban',
 'art',
 'help',
 'optimism',
 'strength',
 'love',
 'traveling',
 'burstiness',
 'ppl',
 'syntax_depth',
 'ttr',
 'semantic_mean',
 'semantic_std']

In [23]:
test

,Text,model_builder,is_AI,gain,beauty,government,urban,art,help,optimism,strength,love,traveling,burstiness,ppl,syntax_depth,ttr,semantic_mean,semantic_std
0,Comments\nThe U.S. bombings thatended World Wa...,Human_story,0,0.002148,0.000000,0.008116,0.002387,0.000716,0.000239,0.001910,0.002865,0.000955,0.002865,11.681473,26.433987,6.700508,0.352162,0.327896,0.195175
1,new video loaded:Messages From Quarantine\ntra...,Human_story,0,0.000000,0.000000,0.001037,0.001037,0.001037,0.001037,0.003112,0.002075,0.005187,0.003112,11.348011,21.833242,4.918919,0.416031,0.237706,0.155878
2,"Supported by\nRoberta Karmel, First Woman Name...",Human_story,0,0.000000,0.000000,0.026415,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.007547,11.317084,22.159660,7.583333,0.600707,0.281305,0.188419
3,Supported by\nContests\nSummer Reading Contest...,Human_story,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.002681,0.005362,0.000000,0.000000,0.005362,12.922714,28.709743,6.555556,0.475827,0.300525,0.143346
4,The Week on Instagram\n@heislerphoto was one o...,Human_story,0,0.000000,0.000000,0.015385,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.347904,94.671150,6.666667,0.761194,0.203593,0.170377
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51176,**Title: Discovering Dumpling Delights: Unveil...,GPT_4-o,1,0.003534,0.007067,0.000000,0.014134,0.010601,0.001767,0.003534,0.001767,0.005300,0.005300,10.386892,17.900406,6.296296,0.518261,0.409363,0.144570
51177,Error: Error communicating with OpenAI: HTTPSC...,GPT_4-o,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.037037,0.000000,0.000000,0.000000,59.434940,4.333333,0.820513,0.000000,0.000000
51178,Error: Error communicating with OpenAI: HTTPSC...,GPT_4-o,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.037037,0.000000,0.000000,0.000000,58.192219,4.333333,0.820513,0.000000,0.000000
51179,"**Is It Storage or Art? If It’s Hard to Tell, ...",GPT_4-o,1,0.001351,0.002703,0.001351,0.000000,0.027027,0.006757,0.002703,0.000000,0.005405,0.004054,8.357401,25.090992,6.075000,0.472848,0.417118,0.126422
51180,**Title: Evacuation Concludes in Aleppo as Ass...,GPT_4-o,1,0.004016,0.000000,0.012048,0.008032,0.000000,0.002008,0.004016,0.008032,0.000000,0.004016,10.318291,17.036764,7.347826,0.537549,0.381032,0.124662